apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
# - deployment.yaml

namespace: staging

commonLabels:
  app.kubernetes.io/component: nginx
  app.kubernetes.io/part-of: myapps

images:
- name: nginx
  newTag: "1.21"

patches:
- patch: |-
    - op: add
      path: /metadata/annotations/reloader.stakater.com~1auto
      value: "true"
  target:
    kind: Deployment
    labelSelector: app.kubernetes.io/name=ngnix
    name: nginx